####################
# 配置文件   #
####################
# Zeromore initialization file, generally called config.ini, is responsible for
# configuring many of the aspects of Zeromore behavior.

	 
    name 		=	"zeromore server" 
    enable 		= 	true 
    status 		= 	"dev"
    version		=	"1.0"
    loglevel	=	"error"
    rpc_type	=	"go"  # string | flatbuffer 
    pack_type	=	"bufferio"
	
	[log]
		log_level	=	"error"
		log_behind_type = "mongodb"  
		mongodb_host = "localhost"
		mongodb_port = "27017"
	
	[admin]
		http_port = "9090"
	    
    [connector]
    	websocket_port 	= 7898  
    	socket_port    	= 7002  
    	max_conections 	= 1024
    	max_packet_rate	= 100
    	max_conntions_ip= 100
      	max_packet_rate_unit = 10  
      	
    [object]
    	data_type 	= "redis"  #  Mysql| redis | monogo  
		redis_host 	= "127.0.0.1"
		redis_port 	= "6379"
		redis_password = ""
		monogo_host = "localhost"
		monogo_port = 27017 
		mysql_host 	= "localhost"
		mysql_port 	= 3306
		mysql_password = ""
		    

	[worker_server]
	    servers = [ ["127.0.0.1","8001"], ["127.0.0.1", "8002"], ["127.0.0.1", "8003"],
		 ["127.0.0.1", "8004"] , ["127.0.0.1", "8005"] , ["127.0.0.1", "8006"] , ["127.0.0.1", "8007"]  , ["127.0.0.1", "8008"]  , ["127.0.0.1", "8009"]  ,
		 ["127.0.0.1", "8010"], ["127.0.0.1", "8011"]  , ["127.0.0.1", "8012"]  , ["127.0.0.1", "8013"]  , ["127.0.0.1", "8014"]  , ["127.0.0.1", "8015"]    ]
	 
	[hub] 
    	hub_host = "127.0.0.1" 
    	hub_port = "7302" 
 
	[area]
		init_area = ["area-global", "area-global2", "area-global3"]
		
		
		
      