    # demo webim 数据库连接配置

    database 	=	"webim"
    host        =   "127.0.0.1"
    user 		= 	"root"
    password 	= 	""
    port		=	"3306"
    charset	    =	"utf8mb4_unicode_ci"
    timeout	    =	"30"
